### PR TITLE
Merge tide module 

### PR DESCRIPTION
**Pull request by socoyjonathan**
Add tide module to geoclaw python directory.

### CODE REVIEW

**Comment by mandli** [comment]
@rjleveque can you help to review this given your experience with tidal things?  Also perhaps invite Loyce?

**Comment by mandli** [comment]
@socoyjonathan can you provide a Jupyter notebook to demonstrate the use of these routines?  I know you already have a notebook that does so but something that could be included in the apps repository and can be referred to for documentation would be great.

**Comment by rjleveque** [comment]
Yes, we'll take a look.  Thanks for working on this @socoyjonathan!

**Comment by rjleveque** [comment]
One observation about the new `tide.py` module... it has functions `retrieve_water_levels` and `retrieve_predicted_tide` that together seem to replicate the functionality of `geoclaw.util.fetch_noaa_tide_data` but with fewer options and error checking. So I was wondering if you're aware of that routine and how best to merge them perhaps?  It makes sense to move that out of `util` now that there will be a  `tide` module.

https://github.com/clawpack/geoclaw/blob/e8d0bf30b0f1676962440743e5c0cd1df3225ac0/src/python/geoclaw/util.py#L200

The error checking seemed important due to some examples where things failed, see befbfbf25. 

Also note the tests in [tests/test_util.py](https://github.com/clawpack/geoclaw/blob/master/tests/test_util.py), which you might want to update.

**Comment by mandli** [comment]
I was thinking about this as well.  I fully support moving the routine although maybe we should consider having the function imported into `util` just so that anyone using it will not break expected functionality.

**Comment by socoyjonathan** [comment]
@rjleveque. Thank you for your constructive review, Professor LeVeque! I have incorporated your amazing suggestions in ```tide.py``` and ```util.py```. Let me know your thoughts! 

@mandli. I have taken your suggestion into account too! Thank you!

**Comment by rjleveque** [comment]
Thanks for working on this.  I added a few comments to the notebook and rendered it [here](https://depts.washington.edu/clawpack/samples/Tide_Module_Examples_2022-03-09.html).  If you search for RJL in that file you can find them.

**Comment by mandli** [comment]
Moved over to [tidal-examples](https://github.com/clawpack/tidal-examples).

**Pull request closed without merging**
