### PR TITLE
Implement Batch Gauge Output

### PR DESCRIPTION
**Pull request by mandli**
Please see clawpack/clawpack#91 for details on the features implemented in this PR.  Also wait for that PR to be merged before merging this one as it is multi-repository dependent.

### CODE REVIEW

**Comment by rjleveque** [comment]
Seems to work in the `examples` directory, but in `tests` I get various errors, e.g....

```
======================================================================
FAIL: Test bowl-slosh example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rjl/git/clawpack/geoclaw/tests/bowl_slosh/regression_tests.py", line 57, in runTest
    self.check_gauges(save=save, gauge_id=1, indices=(2, 3))
  File "/Users/rjl/git/clawpack/clawpack/clawutil/test.py", line 335, in check_gauges
    rtol=tolerance, verbose=True)
  File "/Users/rjl/anaconda/envs/jupyter/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/rjl/anaconda/envs/jupyter/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-14, atol=0

(mismatch 100.0%)
 x: array([ 5.141944,  5.141944])
 y: array([ 5.144379,  5.144379])
```

Does it work ok for you @mandli?

**Comment by rjleveque** [comment]
The regression data in `tests/bowl_slosh/regression_data/gauge00001.txt` looks odd , especially the first column but also the formatting is not the same as what the code now produces when running the tests.

```
# gauge_id= 1 location=( 0.5 0.5 ) num_eqn= 4
# Columns: level time q(1 ... num_eqn)
4611686018427387904 0.0 0.07497749 0.0 0.05251101 0.025
4611686018427387904 0.0001 0.07498449 -7.355608e-06 0.05251591 0.025007
etc.
```

**Comment by mandli** [comment]
I had seen that earlier, it was a buffer overrun that I thought I had fixed.  It's possible I did not catch it for this particular example though so I will take a look.

**Comment by rjleveque** [comment]
I had to merge by hand so this is now replaced by #211

**Pull request closed without merging**
