### PR TITLE
Add UNSET option to flag2refine2

### PR DESCRIPTION
**Pull request by BrisaDavis**
Updating flag2refine2 to work with new UNSET flag in the amrflags array.

### CODE REVIEW

**Comment by rjleveque** [comment]
The tests pass on my laptop.  They might not pass on travis until the PR https://github.com/clawpack/amrclaw/pull/224 has been merged in and then clawpack/clawpack updated.  The way travis works it clones the master branch of amrclaw and doesn't see the new code in amrclaw until it's merged.

So let's hold off on merging this until https://github.com/clawpack/amrclaw/pull/224 is merged. In the meantime I'll review it and perhaps @mjberger can too.

**Comment by rjleveque** [comment]
Note:

1. This addresses #298.   Moreover `flag2refine` is now called only if at least one cell on the patch is set to `UNSET`.  If the entire patch has already been flagged with each cell marked as `DOFLAG` or `DONTFLAG` by means of the "regions", then this routine is not called on the patch, potentially speeding things up.  (Particularly once adjoint flagging is merged in, which is more expensive than what is currently done in `flag2refine`).

2. This preserves the way that flags are added to areas covered by a topo, dtopo, or qinit file. Note that this only checks if the level is below `minlevel` and the flag should be set to `DOFLAG`.  The code has apparently never used the `maxlevel` values associated with one of those files.

3. In the future we should still think about deprecating the topo, dtopo, or qinit file specification of regions since it causes confusion?

**Comment by rjleveque** [comment]
Travis throws compile errors in e.g. `tests/bowl_slosh`, but it compiles fine for me so I'm not sure what's going on.

**Comment by mandli** [comment]
All the targets are failing to build because of the following:
```
Makefile:71: warning: overriding commands for target `all'
/home/travis/build/clawpack/geoclaw/clawpack/clawutil/src/Makefile.common:280: warning: ignoring old commands for target `all'
/home/travis/build/clawpack/geoclaw/clawpack/geoclaw/src/2d/shallow/flag2refine2.f90:26.37:
    use amr_module, only: mxnest, t0, DOFLAG, UNSET
                                     1
Error: Symbol 'doflag' referenced at (1) not found in module 'amr_module'
/home/travis/build/clawpack/geoclaw/clawpack/geoclaw/src/2d/shallow/flag2refine2.f90:26.45:
    use amr_module, only: mxnest, t0, DOFLAG, UNSET
                                             1
Error: Symbol 'unset' referenced at (1) not found in module 'amr_module'
/home/travis/build/clawpack/geoclaw/clawpack/geoclaw/src/2d/shallow/flag2refine2.f90:100.46:
                        amrflags(i,j) = DOFLAG
                                              1
Error: Symbol 'doflag' at (1) has no IMPLICIT type
/home/travis/build/clawpack/geoclaw/clawpack/geoclaw/src/2d/shallow/flag2refine2.f90:99.87:
        if ( ds < R_refine(m) .and. level <= m .and. amrflags(i,j) == UNSET) th
                                                                           1
Error: Symbol 'unset' at (1) has no IMPLICIT type
make: *** [/home/travis/build/clawpack/geoclaw/clawpack/geoclaw/src/2d/shallow/flag2refine2.o] Error 1
```

**Comment by rjleveque** [comment]
@mandli: I don't think so -- are you sure you are compiling against the latest master branch of amrclaw?  Those variables are now declared in `amrclaw/src/2d/amr_module.f90`.

**Comment by mandli** [comment]
I just meant that's what travis is saying the problem is.  Isn't this due to AMRClaw not being updated on clawpack/clawpack though?

**Comment by rjleveque** [comment]
Passing!

**Pull request merged**
