### PR TITLE
fix typo in SubFault.dynamic_slip

### PR DESCRIPTION
**Pull request by rjleveque**
very minor so I'll merge it in.

### CODE REVIEW

**Comment by mandli** [comment]
Crazy, how did we not catch that?

**Comment by mandli** [comment]
Looks like the tests failed due to not including one of @ketch's new PRs?

**Comment by rjleveque** [comment]
The `.travis.yml` file still uses `python setup.py symlink-only` which has been deprecated. Is changing this in a PR on geoclaw?  I don't see it.

**Comment by rjleveque** [comment]
@mandli and @ketch: Changing `symlink-only` to `git-dev` on the `python setup.py` line worked, so if this seems like the right way to fix it we can do the same in amrclaw.  It's already doing that in classic.

**Comment by mandli** [comment]
Looks like this works but @ketch would know better than I if this is the right thing.  In PyClaw it looks like a `python setup.py install` is done in PyClaw.

**Comment by ketch** [comment]
I think that's fine. It might be even nicer to just explicitly call git submodule init + update so there is no mystery about what is going on here.

**Comment by ketch** [comment]
In fact I would favor removing the git-dev option for the reason I just stated.

**Comment by rjleveque** [comment]
Is this better?

**Comment by ketch** [comment]
Seems better to me -- no reason to hide two simple and standard commands inside one very non-standard function.

**Pull request merged**
