### PR TITLE
topotools unstructured bugs

### PR DESCRIPTION
**Pull request by rjleveque**
In trying to update the notebook
  http://nbviewer.ipython.org/url/clawpack.github.io/notebooks/topotools_examples.ipynb
I ran into this bug.

But after fixing, it gives a funny result.  The last figure looks wrong

@mandli: can you investigate?

unstructured

### CODE REVIEW

**Comment by mandli** [comment]
Huh, will investigate.

**Comment by mandli** [comment]
@rjleveque On a related note, have you moved the topography examples?

**Comment by mandli** [comment]
Try using the minimum instead of the maximum in your modification.

**Comment by rjleveque** [comment]
Yes, that fixed it.

**Pull request merged**
