### PR TITLE
Add time scale to timespan routine for GE

### PR DESCRIPTION
**Pull request by donnaaboise**
Compatible with changes to VisClaw (plotpages.py)

### CODE REVIEW

**Comment by mandli** [comment]
Does this require https://github.com/clawpack/visclaw/pull/224?

**Comment by donnaaboise** [comment]
Well, the `timespan` routine is called by `plotpages`, and is used by `plot2kml`.  So probably it should be with visclaw?  But where?  I didn't want to put it in plotpages, but am not sure where else it should go.  This routine figures out the correct time stamp to use for time frames in KML animations (viewed in Google Earth).

**Comment by mandli** [comment]
Things like this are tricky to know where to put them.  I am not so concerned about that but I wanted to make a note that there is a cross-repository dependency here.  It looks like it won't be too big of a deal in any case.  I think we are also hoping to get a release done before the end of May.  The code looks fine to me so if you want to merge both of these I am fine with that.

**Comment by donnaaboise** [comment]
Can you merge this in?  I don't have admin privileges

**Comment by mandli** [comment]
Did you mean to close this?

**Comment by donnaaboise** [comment]
ER ... yes ... but only because I thought we were done.  Can you merge in this PR?

**Pull request closed without merging**
