### PR TITLE
Merged fix proper nesting changes and fix timers

### PR DESCRIPTION
**Pull request by rjleveque**
Combination of mjberger/fixProperNesting and mjberger/fixTimers, with merges from recent changes to master.

Travis tests might not pass until clawpack/amrclaw#174 is merged and clawpack/clawpack updated.

Replaces #223.

### CODE REVIEW

**Comment by mandli** [comment]
You may need to do a super-repository commit to get this all to pass the tests.

**Comment by rjleveque** [comment]
@mandli: Travis is failing in the classic repository and nosetests also don't pass there on my laptop, perhaps due to changes in the testing framework?

```
TypeError: check_frame() got an unexpected keyword argument 'regression_data_path'
```

I'm going to merge this so I can continue testing geoclaw, but we need to fix classic too.

**Comment by mandli** [comment]
We did merge in a different way to store gauge files (https://github.com/clawpack/clawutil/pull/102), maybe that has something to do with it?

**Comment by mandli** [comment]
Not sure where this stands now, can we merge it in?

**Comment by mjberger** [comment]
Randy was working on this friday - the two are somehow out of sync.

 — Marsha

**Comment by mandli** [comment]
This is out of sync?

**Comment by rjleveque** [comment]
They are out of sync only because amrclaw has had things merged but not yet geoclaw (this PR). But I updated clawpack/clawpack after amrclaw and the Travis tests are now passing on this PR so I think it can be merged in.

**Pull request merged**
