### PR TITLE
Add back default land bounds

### PR DESCRIPTION
**Pull request by mandli**
In some instances the land bounds were not being set making the land plotting janky (technical term for awful).

### CODE REVIEW

**Comment by mandli** [comment]
Something is wrong with the colorbars that I need to fix (they are off center).  Looking into it.

**Comment by mandli** [comment]
@rjleveque are you seeing this in any other examples?  I am somewhat suspicious that this might be related to the `pobj` issue (https://github.com/clawpack/visclaw/pull/219).  Note that I am seeing this in both 2.7 and 3.x but for matplotlib version 2.0.x.

figure_1003

**Comment by mandli** [comment]
One thing to note here is that in this particular example I *try* to set the colorbar ticks manually.  Not doing this does not fix the problem but makes it mildly better.

**Comment by rjleveque** [comment]
@mandli: Do you mean the fact that colorbar colors aren't centered about 0?  But it looks like the ocean is white indicating no disturbance at some negative elevation.  Maybe you have `sea_level` set to something other than 0 and the setplot is set to center around that value (I do this for some situations).

**Comment by mandli** [comment]
I think I figured out the problem.  For the Ike example `sea_level != 0.0` but in matplotlib version < 2 I translated the colorbar so that it looked like `sea_level` was the zero point but plotted as zero.  It appears that the colorbar now always takes the `vmin` and `vmax` from the `pobj` rather than respecting `clim`.  I am not sure if this is completely true but testing seems to indicate this to be the case.  

So it's not probably related to clawpack/visclaw#219 but another fix for the plotting needs to be made.  New commit forthcoming.

**Comment by mandli** [comment]
This is now working in Python2 but Python3 has the problem in clawpack/visclaw#219 as described.  The fix there seems to work for Python2 and Python3.

**Pull request merged**
