### PR TITLE
Only read part of netCDF inside domain

### PR DESCRIPTION
**Pull request by bolliger32**
This is useful particularly for the use case where you have a global DEM that you want to repeatedly use as the lowest-resolution "base" topography for multiple storm runs, but you don't want to read in the entire world of topography if each domain is much smaller.

### CODE REVIEW

**Comment by mandli** [comment]
Are you up to possibly modifying the storm surge test case to utilize this feature with a downloaded NetCDF file?

**Comment by bolliger32** [comment]
@mandli sure. You mean the test under `storm_surge`, which currently uses an ascii topo?

**Comment by mandli** [comment]
Yes, if you can do it easily.

**Comment by bolliger32** [comment]
Doable, but the easier thing to do might be to adjust the netcdf_topo test? We could just make the `bowl.nc` much bigger. Do you want this to be done specifically with a downloaded netcdf or would the bowl option work? Also, how were you thinking we'd test that it only read in the right amount of data? I think that might be hard. Or would you just want to maybe save two .nc files (one the correct size for the domain and one bigger) and then test that the outputs are the same? That would be more doable

**Comment by mandli** [comment]
Whatever is easiest to get at least a “not fail” test in there.

**Comment by bolliger32** [comment]
ok just made the bowl.nc file have a bigger range in the netcdf_topo test. This is confirming that the model results are the same, but doesn't necessarily confirm that the new code is working to only load in a subset of the data. To confirm that I think we'd need to monitor memory or somehow add a flag within the fortran code to save the extent of the netcdf that was read, no? That seems probably overkill to me but if you think it's important I'm happy to take that on. I think first order test, however, is to make sure we didn't change the results, which I think is accomplished with just making the bowl.nc file have a larger extent and verifying that the tests still pass.

**Comment by mandli** [comment]
I think if we can confirm it working once (memory wise maybe) then as long as it continues to not break we are good.  Worst case scenario is that it cuts too far.

**Comment by bolliger32** [comment]
I have confirmed it works memory-wise on our runs. And I think the fact that the tests still pass (including gauge results) suggests that nothing is cutting too far? Happy to implement other tests if you have some in mind though

**Comment by mandli** [comment]
Nope, I think this looks good.

Also did you know that shift-cmd-return will comment and close a PR?

**Comment by bolliger32** [comment]
> Also did you know that shift-cmd-return will comment and close a PR?

Haha, I do now!

**Comment by mandli** [comment]
...and cmd-return just comments.  The wonders of keyboard short-cuts.

**Comment by rjleveque** [comment]
Haven't tried it yet, but looks very useful. Thanks!

There are a number of related things I would love to be able to do. See #296.

**Pull request merged**
