### PR TITLE
Set orientation of TC according to hemisphere

### PR DESCRIPTION
**Pull request by tovogt**
This PR makes sure that the TC storm vortex rotates counter-clockwise on the northern and clockwise on the southern hemisphere (see #514).

### CODE REVIEW

**Comment by mandli** [comment]
@tovogt I am wondering if we can do this more generally and simply have a sign value applied to the latitude?

**Comment by tovogt** [comment]
Hm, I'm not sure what you mean. You can transfer the check `y >= 0` to a different place, but you will never get rid of it. For example, you can change the function `calculate_polar_coordinate` to set `theta = theta + 180` if `y < 0`. This will generate the same result in the end, but the function doesn't strictly compute polar coordinates any longer, which is really confusing if you need it for something else in the future.

**Comment by mandli** [comment]
Yes, I guess that's what I was wondering instead of having it in each wind model instead.  Now that I look at what you did though more carefully I think you basically did this.

**Comment by mandli** [comment]
Thanks BTW!

**Pull request merged**
