### PR TITLE
Change ModuleNotFoundError to ImportError

### PR DESCRIPTION
**Pull request by mandli**

### CODE REVIEW

**Comment by rjleveque** [comment]
With this fix tests pass on my laptop in Python 2 but not in 3.6, where I get:

```

======================================================================
ERROR: Test reading and writing of storm formats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/rjl/git/clawpack/geoclaw/tests/test_storm.py", line 143, in test_storm_IO
    raise e
  File "/Users/rjl/git/clawpack/geoclaw/tests/test_storm.py", line 118, in test_storm_IO
    test_storm = storm.Storm(input_path, file_format=file_format, **kwargs)
  File "/Users/rjl/git/clawpack/clawpack/geoclaw/surge/storm.py", line 193, in __init__
    self.read(path, file_format=file_format, **kwargs)
  File "/Users/rjl/git/clawpack/clawpack/geoclaw/surge/storm.py", line 245, in read
    getattr(self, 'read_%s' % file_format.lower())(path, **kwargs)
  File "/Users/rjl/git/clawpack/clawpack/geoclaw/surge/storm.py", line 534, in read_ibtracs
    ds.usa_rmw >= 0,-1).values
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/core/common.py", line 607, in where
    raise NotImplementedError("The optional argument 'other' has not "
NotImplementedError: The optional argument 'other' has not yet been implemented

----------------------------------------------------------------------
Ran 30 tests in 43.560s

FAILED (SKIP=1, errors=2)
```

But I'll go ahead and merge this and then update https://github.com/clawpack/clawpack/pull/133.

**Comment by mandli** [comment]
@bolliger32 can you look into this and see what might the difference in versions be?

**Comment by bolliger32** [comment]
Ah looks like that's an xarray dependency issue. the `DataArray.where()` method filling with 'other' was implemented starting in version 0.10.0.

**Comment by mandli** [comment]
@bolliger32 ug, version issues are the worse.  Is there an easy way around it?  Should we also test for versions?

**Comment by bolliger32** [comment]
@mandli how are dependencies handled now? If it's a hassle to change to a later version of xarray for dependency, it's pretty easily remedied. Can use `np.where` instead of `DataArray.where`. Hopefully that's the only xarray version issue

**Comment by mandli** [comment]
The tests are handled via the travis script which I think can force a version.  We should add a check for the version number though unless it's easy to code around.

**Comment by bolliger32** [comment]
it's a quick one-line swap to np.where. Should I do that and submit a PR? Which branch/fork should I submit the PR to?

**Comment by mandli** [comment]
Yeah, if we can remove the version problem all together that would be best.  I would suggest doing a new PR that is branched from master as the `new-storm-module` branch has now been merged in.

**Comment by bolliger32** [comment]
Cool just did that

**Pull request merged**
