### PR TITLE
WIP: Test travis adjoint

### PR DESCRIPTION
**Pull request by rjleveque**
Modify tests/chile2010_adjoint/regression_tests.py to copy adjoint subdirectory and run that code as part of setUp.

Contains some debug print statements too.

### CODE REVIEW

**Comment by mandli** [comment]
I am getting the following error
```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
```
when running `BowlSlosh` test.  Can you reproduce this?  I am using the following flags for `gfortran`:
```
FFLAGS = -O0 -W -Wall -fbounds-check -fcheck=all -pedantic-errors -Wunderflow -fbacktrace -ffpe-trap=invalid,zero,overflow -g
```

**Comment by rjleveque** [comment]
No I can't reproduce, that example runs fine for me with those flags.

**Comment by mandli** [comment]
Hmm, let me take another crack at it then.

**Comment by mandli** [comment]
Ok, not getting that error anymore (not sure what was going on).  I am now getting the same error that Travis is getting.  Attached is the gauge file, it looks like it only differs a bit.
[gauge00001.txt](https://github.com/clawpack/geoclaw/files/3200230/gauge00001.txt)

**Comment by rjleveque** [comment]
@mandli, can you compare what you get from running the adjoint code, in 
```
tests/chile2010_adjoint/adjoint/_output/gauge00001.txt
```
 with what's in 
```
tests/chile2010_adjoint/adjoint/regression_data/gauge00001.txt
```
which is also at:
https://github.com/rjleveque/geoclaw/blob/test_travis_adjoint/tests/chile2010_adjoint/adjoint/regression_data/gauge00001.txt

I'd like to know whether the adjoint solution seems to be the same and the difference only appears in the forward solver, or if the adjoint solution is different.

**Comment by mandli** [comment]
As far as I can tell the adjoint gauges match.  You may want to add some code though to also copy the adjoint results into the directory copied locally if failure is reached.  I ended up running the adjoint code directly to compare so I am not entirely sure if I am comparing what is found in the test.

**Comment by mandli** [comment]
Nevermind, you are copying the test data.  I reran it just to be sure but I diffing the gauges from the adjoint problem reveals nothing.

**Comment by mandli** [comment]
Do you want to remove the `@wip` on the test now that it is passing?

**Comment by rjleveque** [comment]
@mandli: I diffed things from the tar file you sent me and the adjoint solution was identical, but for some reason the forward solution had variations in the 6th decimal place or so although the all the grids created and output times are identical.

I noticed from `_output/claw_git_status.txt` that you had an earlier branch `adjoint_qwave_updates` checked out rather than this update, but when I checked out that branch and ran the test I still get the same results that match the regression data.

So the tests now pass because I changed `rtol` and `atol` to `1e-5`.  I think at this point we should merge it in and go ahead with the release.

But after merging this I want to move the new Riemann solver to the riemann repository and then update clawpack/clawpack and hope it still works.

**Comment by mandli** [comment]
Sound good.

**Pull request merged**
