### PR TITLE
Update multilayer example Makefile

### PR DESCRIPTION
**Pull request by mandli**
This updates to the new version of the Makefiles

### CODE REVIEW

**Comment by rjleveque** [comment]
It runs ok although it gives a warning:
```
Makefile:48: Extraneous text after `else' directive
```

The original `Makefile` does too.

**Comment by mandli** [comment]
Yeah, it's a strange leftover from older Makefile syntax that sometimes gets triggers (and sometimes causes failures completely).  I will try to find a solution to this.

**Comment by mandli** [comment]
@rjleveque I think I fixed this.  Let me know if you still see the warning.

**Comment by rjleveque** [comment]
That fixed it.

**Pull request merged**
