### PR TITLE
prevent underflow in set_holland_1980_fields

### PR DESCRIPTION
**Pull request by delgadom**
surge/model_storm_module.f90:set_holland_1980_fields

current implementation can throw an underflow error if `-Wunderflow` compiler flag is set, as `exp(-(mwr/r)**B)` can be an extremely small value.

```fortran
! Set pressure field
aux(pressure_index,i,j) = Pc + dp * exp(-(mwr/r)**B)

! Speed of wind at this point
wind = sqrt((mwr/r)**B &
        * exp(1.d0 - (mwr/r)**B) * mws**2.d0 &
        + (r * f)**2.d0 / 4.d0) - r * f / 2.d0
```
Limiting the ratio `(mwr/r)` to be less than 10 prevents this error while not significantly affecting wind or pressure estimates.

```fortran
! use a threshold of 10 to prevent underflow
IF ((mwr/r) > 10) THEN
    ! Set pressure field
    aux(pressure_index,i,j) = Pc

    ! Speed of wind at this point
    wind = sqrt((r * f)**2.d0 / 4.d0) - r * f / 2.d0
ELSE
    ! Set pressure field
    aux(pressure_index,i,j) = Pc + dp * exp(-(mwr/r)**B)

    ! Speed of wind at this point
    wind = sqrt((mwr/r)**B &
            * exp(1.d0 - (mwr/r)**B) * mws**2.d0 &
            + (r * f)**2.d0 / 4.d0) - r * f / 2.d0
END IF
```

### CODE REVIEW

**Comment by mjberger** [comment]
Would't you prefer  set to zero, and no trigger of underflow, rather than setting a limit?
I set the traps for everything  EXCEPTN an underflow.  Why do that?


 — Marsha

**Comment by mandli** [comment]
One of the problems we ran into was a bus error that APPEARS to be caused by the underflow of the evaluation of the `exp` function.  One thing I had perhaps thought about doing instead was to do test the argument to the `exp` function and then set it to zero if the argument was small enough.

**Comment by mjberger** [comment]
Did you test on other compilers?

 — Marsha

**Comment by mandli** [comment]
On the list...  The `gfortran` compiler did catch the underflow exception when enabled though.

**Comment by mandli** [comment]
@delgadom are we still having issues with this?

**Comment by delgadom** [comment]
@mandli sorry to drop this - thanks for the ping! We haven't run with the `-Wunderflow` flag since April - will check and get back to you.

**Comment by delgadom** [comment]
If I'm remembering correctly, the intel compiler did not raise an error when you ran this, @mandli. We ran into the issue because we're using gfortran.

**Comment by mandli** [comment]
Yeah, I figured.  We should probably try it again and see if it's a particular version of gfortran.

**Comment by mandli** [comment]
Going to close this as it seems to be compiler (version) dependent for the moment.  If this ends up becoming an issue we can reopen.

**Pull request closed without merging**
