### PR TITLE
Tohoku example

### PR DESCRIPTION
**Pull request by donnaaboise**
This example runs an example from the Tohoku earthquake and tsunami.  It includes 

* setrun.py with gauges set to 1123 and 5680 (Maui harbor)

* A Jupyter notebook that reproduces a few of the plots in the Arcos/LeVeque paper.   This notebook has links to the archive data for the paper stored on Zenodo. 

* Visualization is set up for Matlab,Google earth and VisClaw.

### CODE REVIEW

**Comment by rjleveque** [comment]
Thanks @donnaaboise!  I'll take a closer look, but a couple quick questions:

 - Do you think this should go in `geoclaw/examples` rather than in the new repository [tsunami-examples](https://github.com/clawpack/tsunami-examples) we discussed as a submodule of `apps`?  I don't know how long it takes for this setup to run, but maybe too slow for the examples directory?
 - Did you forget to commit the Jupyter notebook, I didn't find it.
 - `maketopo.py` tries to download a non-existent file, http://depts.washington.edu/clawpack/geoclaw/topo/etopo/hawaii_6s.txt, did you want me to upload that?
 - You said visualization is set up for Matlab, should there be a `.m` file?

**Comment by donnaaboise** [comment]
@rjleveque 
* I had in mind that it would go to your examples-tsunami repo, but maybe the fact that I did the pull request from the geoclaw/examples directory confused things.  Dependiing on the how amr_max is set, the run can take from about 10 minutes (amp_max=4) to an hour (amp_max = 6).  
* I committed the Jupyter notebook - let me know how it looks, especially if there are details on the model and your paper that I don't have quite right.  
* The setrun file I got from your archive code references the hawaii_6s.txt file, so I simply included it.  It doesn't look like it is needed for this example, though, so I commented it out in setrun.py and maketopo.py. 
* I've added the Matlab files.  I also added a few files to visclaw/src/matlab that will be needed as well.   I'll do a separate PR for those files.

**Comment by rjleveque** [comment]
I fixed some URLs in https://github.com/donnaaboise/geoclaw/pull/1
The `hawaii_6s.txt` file still seems to be used, so I fixed the URL for that one too.

There are two notebooks `compare_results.ipynb` and	`detide.ipynb` that seem to have virtually identical code but different text. Which one is the right one to include?

I have also started including Jupyter notebooks in some examples and it's great to do that.  But I might suggest committing the notebook with the output stripped out (by clearing output before saving or I always use [nbstripout](https://github.com/kynan/nbstripout).  Your notebook is relatively small but they can get huge if there are many plots and particularly if it includes animations in the output.  Also, it's much easier to use e.g. `git diff` to see what has changed in a notebook if it doesn't have all the embedded plots and other output included.

I suggest that eventually we also include a rendered html version of the notebook in the gallery, and a README file that points to that as well as the notebook source.  See for example [this gallery example](http://www.clawpack.org/gallery/_static/geoclaw/examples/tsunami/eta_init_force_dry/README.html) that goes along with the README.rst and notebooks files in `$CLAW/geoclaw/examples/tsunami/eta_init_force_dry`.  (There may be better ways to do this, I'm open to suggestions!)

Regarding which repository, since you added this to your geoclaw/examples directory and did the PR in the geoclaw repo that's where it will be if we merge this PR.  If we want it in repository https://github.com/clawpack/tsunami-examples then you will have to fork that repo, add and commit it there, and then do a PR from your fork to https://github.com/clawpack/tsunami-examples.

I just got this running and now will take a closer look at the notebook and plots, and think some more about where it's best to put this.

Thanks again, it's nice to have this example cleaned up and made more stand-alone!

**Comment by donnaaboise** [comment]
@rjleveque 
* I thought I checked that `hawaii_6s.txt` was not required (removed it from my scratch and make topo files).   But I evidently I missed something.  Thanks for fixing the URLs.
* I removed the `detide.ipynb` notebook and stripped output from `compare_results.ipynb`.  
* Does `make input` replace `make data`?  Should I create a `make_input_files` notebook?  Or is it enough to generate an HTML file from the notebook I have already created?  
* Let me know where you think the PR should go. 

I didn't get the `fgmax` settings working from the setrun file, so those lines are commented out.   I'd welcome any assistance on this, if this should be included.

**Comment by rjleveque** [comment]
@donnaaboise:  `make data` is still the command to turn `setrun.py` into the `.data` files needed for geoclaw.  I've been using names like `make_input_files.ipynb` for notebooks that create some of the input files that are referenced in `setrun.py`, e.g. if it's necessary to download and pre-process topo files, use the Okada model to generate dtopo files, etc.

Since this example involves downloading a big dataset and is somewhat more specialized, I'm moving it to https://github.com/clawpack/tsunami-examples/tree/master/tohoku2011_hawaii_currents.

The [clawpack/tsunami-examples](https://github.com/clawpack/tsunami-examples) repository will be added as a submodule to [clawpack/apps](https://github.com/clawpack/apps).  Great to finally get something in that repository and I'll try to soon add some other examples too.

I have some more suggested edits to this example, but I'm moving the code as is currently from here to the new location, and then will add new PRs there.

So I'm closing this PR.

**Pull request closed without merging**
